<?php

declare(strict_types=1);

/*
 * This file is part of Pitlane.
 *
 * (c) Maxime Valin
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the servers table and the user_server join table.
 */
final class Version20260724170949 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the servers and user_server tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE servers (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(255) NOT NULL,
                server_name VARCHAR(255) NOT NULL,
                track VARCHAR(255) NOT NULL,
                track_layout VARCHAR(255) DEFAULT NULL,
                cars JSON NOT NULL,
                password VARCHAR(255) NOT NULL,
                admin_password VARCHAR(255) NOT NULL,
                max_clients INT NOT NULL,
                tcp_port INT NOT NULL,
                udp_port INT NOT NULL,
                http_port INT NOT NULL,
                session_type VARCHAR(20) NOT NULL,
                session_duration INT NOT NULL,
                duration_unit VARCHAR(20) NOT NULL,
                weather_graphics VARCHAR(255) NOT NULL,
                ambient_temp INT NOT NULL,
                track_temp INT NOT NULL,
                dynamic_track BOOLEAN NOT NULL,
                track_grip INT NOT NULL,
                tcp_no_delay BOOLEAN NOT NULL,
                register_to_lobby BOOLEAN NOT NULL,
                container_slug VARCHAR(255) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_server_container_slug ON servers (container_slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_server_tcp_port ON servers (tcp_port)');
        $this->addSql('CREATE UNIQUE INDEX uniq_server_udp_port ON servers (udp_port)');
        $this->addSql('CREATE UNIQUE INDEX uniq_server_http_port ON servers (http_port)');

        $this->addSql(<<<'SQL'
            CREATE TABLE user_server (
                user_id INT NOT NULL,
                server_id INT NOT NULL,
                PRIMARY KEY(user_id, server_id)
            )
            SQL);
        $this->addSql('CREATE INDEX IDX_3F3FCECBA76ED395 ON user_server (user_id)');
        $this->addSql('CREATE INDEX IDX_3F3FCECB1844E6B7 ON user_server (server_id)');
        $this->addSql('ALTER TABLE user_server ADD CONSTRAINT FK_3F3FCECBA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_server ADD CONSTRAINT FK_3F3FCECB1844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_server');
        $this->addSql('DROP TABLE servers');
    }
}
