<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the server table.
 */
final class Version20260724170949 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the servers table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE servers (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(255) NOT NULL,
                server_name VARCHAR(255) NOT NULL,
                track VARCHAR(255) NOT NULL,
                track_layout VARCHAR(255) DEFAULT NULL,
                cars JSON NOT NULL,
                password VARCHAR(255) NOT NULL,
                admin_password VARCHAR(255) NOT NULL,
                max_clients INT NOT NULL,
                tcp_port INT NOT NULL,
                udp_port INT NOT NULL,
                http_port INT NOT NULL,
                session_type VARCHAR(20) NOT NULL,
                session_duration INT NOT NULL,
                duration_unit VARCHAR(20) NOT NULL,
                weather_graphics VARCHAR(255) NOT NULL,
                ambient_temp INT NOT NULL,
                track_temp INT NOT NULL,
                dynamic_track BOOLEAN NOT NULL,
                track_grip INT NOT NULL,
                tcp_no_delay BOOLEAN NOT NULL,
                register_to_lobby BOOLEAN NOT NULL,
                container_slug VARCHAR(255) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_server_container_slug ON servers (container_slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_server_tcp_port ON servers (tcp_port)');
        $this->addSql('CREATE UNIQUE INDEX uniq_server_udp_port ON servers (udp_port)');
        $this->addSql('CREATE UNIQUE INDEX uniq_server_http_port ON servers (http_port)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE servers');
    }
}
